### ISSUE TITLE
submission ID with space is not handled properly

### ISSUE THREAD

**Issue by matthew-ardi** [muhammad-alaref/CAM2RESTfulAPI#1]
submitting a job with submission ID with space (for example, ```test 2``` did not work but ```test_2``` worked)

**Comment by malaref** [comment]
The `Submission ID` (as well as the `Username`) should not include spaces. I have added a check to insure both only include alphanumeric characters and underscores. Now, any invalid `Submission ID` or `Username` will be rejected with an appropriate message instead of a random [CAM2DistributedBackend](https://github.com/muhammad-alaref/CAM2DistributedBackend) CLI usage error.

Closed with 94f2baa!
